name: Ungoogled-chromium-android-webview-build-dispatch
on:
  workflow_run:
    workflows: [ "Ungoogled-chromium-android-build-dispatch" ]
    branches: [ master ]
    types:
      - completed
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  build:
    name: Send workflow dispatch to runner repo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Send build request
        env:
          PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          WORKFLOW_NAME: "build-webview"
        run: |
          sleep 30
          .github/workflows/dispatch-request.sh